bot:
  token: "9iwf8s3u8fyojn5fe3eh3xcepa"
  name: "VotelyBot"
  address:
    host: "bot"
    port: "6754"
mattermost:
  url: "http://mattermost:8065"
  teamName: "dev"
database:
  tarantool:
    address: "tarantool:3301"
    user: "guest"
    password: ""